apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: fluxcd-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/praneshragavendar/fluxcd  # Your repo URL
  ref:
    branch: main  # Use the main branch
  secretRef:
    name: flux-git-deploy  # Secret for Git access, replace with your secret name if necessary

