# gotk-sync.yaml
apiVersion: fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/praneshragavendar/fluxcd
  ref:
    branch: main
  secretRef:
    name: flux-git-deploy
