apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxcd-kustomization
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/my-cluster"  # Correct the path here to match the correct location
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-repo
